ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from main import urls as main
urlpatterns = [
    path('', include(main)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from .views import *

from django.conf import settings
from django.conf.urls.static import static
import json
from django.http import HttpResponse

urlpatterns = [
    path('', home, name="home"),
    path('category-list', category_list, name='category-list'),
    path('brand-list', brand_list, name='brand-list'),
    path('product-list', product_list, name='product-list'),
    path('category-product-list/<int:cat_id>', category_product_list,
         name='category-product-list'),
    path('brand-product-list/<int:brand_id>', brand_product_list,
         name='brand-product-list'),
    path('product/<str:slug>/<int:id>', product_detail,
         name='product-detail'),
    path('accounts/signup', signup,
         name='signup'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('cart/', cart_list, name='cart'),
    path('delete-from-cart/', delete_cart_item, name='delete-from-cart'),
    path('update-cart/', update_cart_item, name='update-cart'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images/cat")

    class Meta:
        verbose_name_plural = 'Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width=100px height=100px />' % (self.image.url))

    def __str__(self):
        return self.title


class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images/brand")

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    def color_tag(self):
        return mark_safe('<div style="width:100px; height:30px; background-color:%s; border-radius:5px"></div>' % (self.color_code))

    def __str__(self):
        return self.title


class Size(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=400)
    detail = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class ProductAttribute(models.Model):
    image = models.ImageField(upload_to="images/prod")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.PositiveIntegerField()
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)

    def image_tag(self):
        return mark_safe('<img src="%s" width=100px height=100px />' % (self.image.url))

    def __str__(self):
        return self.product.title


class Banner(models.Model):
    img = models.ImageField(upload_to='images/banner')
    alt = models.CharField(max_length=100)

    def __str__(self):
        return self.alt

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignupForm(UserCreationForm):
    full_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['full_name', 'username', 'password1', 'password2']

main/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import SignupForm
from django.contrib.auth import authenticate, login
import json
from django.http import HttpResponse, JsonResponse
from django.template.loader import render_to_string


# Create your views here.


def home(request):
    banners = Banner.objects.all()
    data = Product.objects.all().order_by('-id')[:4]
    print(len(data))
    context = {
        "data": data,
        "banners": banners
    }
    return render(request, 'index.html', context)


def category_list(reqeust):
    data = Category.objects.all().order_by('-id')
    context = {
        "categories": data
    }

    return render(reqeust, 'category_list.html', context)


def brand_list(reqeust):
    data = Brand.objects.all()
    context = {
        "brands": data
    }

    return render(reqeust, 'brand_list.html', context)


def product_list(reqeust):
    data = Product.objects.all().order_by('-id')
    context = {
        "data": data,
        "product_type": "all",

    }
    return render(reqeust, 'product_list.html', context)


def category_product_list(request, cat_id):
    category = Category.objects.get(id=cat_id)
    data = Product.objects.filter(category=category).order_by('-id')
    context = {
        "data": data,
        "product_type": category.title,
    }
    return render(request, 'product_list.html', context)


def brand_product_list(request, brand_id):
    brand = Brand.objects.get(id=brand_id)
    data = Product.objects.filter(brand=brand).order_by('-id')
    context = {
        "data": data,
        "product_type": brand.title,
    }
    return render(request, 'product_list.html', context)


def product_detail(reqeust, slug, id):
    product = Product.objects.get(id=id)
    context = {
        "data": product,
    }
    return render(reqeust, 'product_detail.html', context)


def signup(request):
    form = SignupForm(request.POST)
    if form.is_valid():
        user = form.save()
        # username = form.cleaned_data.get('username')
        # password = form.cleaned_data.get('password')
        # user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    context = {
        "form": form
    }
    return render(request, 'registration/signup.html', context)


def add_to_cart(request):
    # del request.session['cartdata']
    cart_p = {}
    cart_p[str(request.GET['id'])] = {
        'image': request.GET['image'],
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
    }
    if 'cartdata' in request.session:
        if str(request.GET['id']) in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty'] = int(
                cart_p[str(request.GET['id'])]['qty'])
            cart_data.update(cart_data)
            request.session['cartdata'] = cart_data
        else:
            cart_data = request.session['cartdata']
            cart_data.update(cart_p)
            request.session['cartdata'] = cart_data
    else:
        request.session['cartdata'] = cart_p
    return JsonResponse({'data': request.session['cartdata'], 'totalitems': len(request.session['cartdata'])})

# Cart List Page


def cart_list(request):
    total_amt = 0
    if 'cartdata' in request.session:
        for p_id, item in request.session['cartdata'].items():
            total_amt += int(item['qty'])*float(item['price'])
        return render(request, 'cart.html', {'cart_data': request.session['cartdata'], 'totalitems': len(request.session['cartdata']), 'total_amt': total_amt})
    else:
        return render(request, 'cart.html', {'cart_data': '', 'totalitems': 0, 'total_amt': total_amt})


# Delete Cart Item
def delete_cart_item(request):
    p_id = str(request.GET['id'])
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            del request.session['cartdata'][p_id]
            request.session['cartdata'] = cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty'])*float(item['price'])
    t = render_to_string('ajax/cart-list.html', {'cart_data': request.session['cartdata'], 'totalitems': len(
        request.session['cartdata']), 'total_amt': total_amt})
    return JsonResponse({'data': t, 'totalitems': len(request.session['cartdata'])})

# update Cart Item


def update_cart_item(request):
    p_id = str(request.GET['id'])
    p_qty = request.GET['qty']
    if 'cartdata' in request.session:
        if p_id in request.session['cartdata']:
            cart_data = request.session['cartdata']
            cart_data[str(request.GET['id'])]['qty'] = p_qty
            request.session['cartdata'] = cart_data
    total_amt = 0
    for p_id, item in request.session['cartdata'].items():
        total_amt += int(item['qty'])*float(item['price'])
    t = render_to_string('ajax/cart-list.html', {'cart_data': request.session['cartdata'], 'totalitems': len(
        request.session['cartdata']), 'total_amt': total_amt})
    return JsonResponse({'data': t, 'totalitems': len(request.session['cartdata'])})

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce Bootstrap Template</title>
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'fontawesome-free/css/all.min.css' %}"
    />
    <!-- Bootstrap 4 CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bs4/bootstrap.min.css' %}"
    />
    <!-- Main Jquery -->
    <script type="text/javascript" src="{% static 'jquery.min.js' %}"></script>
    <!-- Bootstrap 4 JS -->
    <script
      type="text/javascript"
      src="{% static 'bs4/bootstrap.min.js' %}"
    ></script>
    <!-- CustomJs -->
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" />
    <script type="text/javascript" src="{% static 'custom.js' %}"></script>
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark"
      style="background-color: purple"
    >
      <div class="container">
        <a class="navbar-brand" href="/">Easy Shop</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link text-white" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'category-list' %}"
                >Categories</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'brand-list' %}"
                >Brands</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'cart' %}"
                ><i class="fa fa-shopping-cart"></i> Cart (<span
                  class="cart-list"
                  >{{request.session.cartdata|length}}</span
                >)</a
              >
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link text-white dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                <i class="fa fa-user"></i>
                {% if user.is_authenticated %} {{user.username}} {% else %} My
                Account {% endif %}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user.is_authenticated %}
                <a class="dropdown-item" href="% url 'my_dashboard' %"
                  >Dashboard</a
                >
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                <a class="dropdown-item" href="{% url 'signup' %}">Signup</a>
                {% endif %}
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top container">
      <div class="row">
        <div class="col-12 col-md">
          <a href="#">Easy Shop</a>
          <small class="d-block mb-3 text-muted">&copy; 2022</small>
        </div>
        <div class="col-6 col-md">
          <h5>Features</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Cool stuff</a></li>
            <li><a class="text-muted" href="#">Random feature</a></li>
            <li><a class="text-muted" href="#">Team feature</a></li>
            <li><a class="text-muted" href="#">Stuff for developers</a></li>
            <li><a class="text-muted" href="#">Another one</a></li>
            <li><a class="text-muted" href="#">Last time</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Resource</a></li>
            <li><a class="text-muted" href="#">Resource name</a></li>
            <li><a class="text-muted" href="#">Another resource</a></li>
            <li><a class="text-muted" href="#">Final resource</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Team</a></li>
            <li><a class="text-muted" href="#">Locations</a></li>
            <li><a class="text-muted" href="#">Privacy</a></li>
            <li><a class="text-muted" href="#">Terms</a></li>
          </ul>
        </div>
      </div>
    </footer>
  </body>
</html>

main/templates/brand_list.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="container my-4">
  <!-- Featured Products -->
  <h3 class="my-4 border-bottom pb-1">Brands</h3>
  <div class="row">
    {% if brands %} {% for brand in brands %}
    <div class="col-md-3 mb-4">
      <div class="card shadow">
        <a href="/brand-product-list/{{brand.id}}"
          ><img
            src="/media/{{brand.image}}"
            class="card-img-top"
            alt="{{brand.title}}"
            width="150px"
            height="150px"
        /></a>
        <div class="card-body">
          <h6 class="card-text">
            <a href="/brand-product-list/{{brand.id}}">{{brand.title}}</a>
          </h6>
        </div>
      </div>
    </div>
    {% endfor %} {% endif %}
  </div>
</main>
{% endblock %}

main/templates/cart.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="container my-4" id="cartList">
  <!-- Featured Products -->
  <h3 class="my-4 border-bottom pb-1">Cart ({{totalitems}})</h3>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Product</th>
        <th>Qty</th>
        <th>Price</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      {% for product_id,item in cart_data.items %}
      <tr>
        <td>
          <img src="/media/{{item.image}}" width="50" />
          <p>
            <a href="/product/{{item.title|slugify}}/{{product_id}}"
              >{{item.title}}</a
            >
          </p>
        </td>
        <td>
          <input
            type="number"
            class="product-qty-{{product_id}}"
            value="{{item.qty}}"
            style="vertical-align: bottom"
          />
          <button
            class="btn btn-sm btn-primary update-item"
            data-item="{{product_id}}"
          >
            <i class="fa fa-sync"></i>
          </button>
          <button
            class="btn btn-sm btn-danger delete-item"
            data-item="{{product_id}}"
          >
            <i class="fa fa-trash"></i>
          </button>
        </td>
        <td>$ {{item.price}}</td>
        <td>$ {% widthratio item.price 1 item.qty %}</td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"></td>
        <th>Total</th>
        <th>$ {{total_amt}}</th>
      </tr>
      {% if totalitems %}
      <tr>
        <td colspan="4" align="right">
          <a href="#" class="btn btn-dark btn-sm"
            >Checkout <i class="fa fa-long-arrow-alt-right"></i
          ></a>
        </td>
      </tr>
      {% endif %}
    </tfoot>
  </table>
</main>
{% endblock %}

main/templates/category_list.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="container my-4">
  <!-- Featured Products -->
  <h3 class="my-4 border-bottom pb-1">Categories</h3>
  <div class="row">
    {% if categories %} {% for cat in categories %}
    <div class="col-md-3 mb-4">
      <div class="card shadow">
        <a href="/category-product-list/{{cat.id}}"
          ><img
            src="/media/{{cat.image}}"
            class="card-img-top"
            alt="{{cat.title}}"
            width="150px"
            height="150px"
        /></a>
        <div class="card-body">
          <h6 class="card-text">
            <a href="/category-product-list/{{cat.id}}">{{cat.title}}</a>
          </h6>
        </div>
      </div>
    </div>
    {% endfor %} {% endif %}
  </div>
</main>
{% endblock %}

main/templates/filters.html
{% load static %}
<script type="text/javascript" src="{% static 'product-filter.js' %}"></script>
<h3 class="mb-4 border-bottom pb-1">Filters</h3>

<!-- Filter 1 -->
<div class="card mb-4">
  <h6 class="card-header">Colors</h6>
  <div class="list-group list-group-flush">
    {% for color in colors %}
    <li class="list-group-item">
      <input
        class="filter-checkbox"
        data-filter="color"
        value="{{color.color__id}}"
        type="checkbox"
      />&nbsp;
      <button
        class="btn"
        style="background-color: {{color.color__color_code}}; margin-top: -5px;"
      ></button>
    </li>
    {% endfor %}
  </div>
</div>
<!-- Filter 2 -->
{% if cats %}
<div class="card mb-4">
  <h6 class="card-header">Categories</h6>
  <div class="list-group list-group-flush">
    {% for cat in cats %}
    <li class="list-group-item">
      <input
        class="filter-checkbox"
        data-filter="category"
        value="{{cat.category__id}}"
        type="checkbox"
      />&nbsp; {{cat.category__title}}
    </li>
    {% endfor %}
  </div>
</div>
{% endif %}
<!-- Filter 3 -->
{% if brands %}
<div class="card mb-4">
  <h6 class="card-header">Brands</h6>
  <div class="list-group list-group-flush">
    {% for brand in brands %}
    <li class="list-group-item">
      <input
        class="filter-checkbox"
        data-filter="brand"
        value="{{brand.brand__id}}"
        type="checkbox"
      />&nbsp; {{brand.brand__title}}
    </li>
    {% endfor %}
  </div>
</div>
{% endif %}
<!-- Filter 3 -->
<div class="card mb-4">
  <h6 class="card-header">Sizes</h6>
  <div class="list-group list-group-flush">
    {% for size in sizes %}
    <li class="list-group-item">
      <input
        class="filter-checkbox"
        data-filter="size"
        value="{{size.size__id}}"
        type="checkbox"
      />&nbsp; {{size.size__title}}
    </li>
    {% endfor %}
  </div>
</div>

main/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% for banner in banners %} {% if forloop.counter == 1 %}
    <li
      data-target="#carouselExampleIndicators"
      data-slide-to="{{forloop.counter}}"
      class="active"
    ></li>
    {% else %}
    <li
      data-target="#carouselExampleIndicators"
      data-slide-to="{{forloop.counter}}"
    ></li>
    {% endif %} {% endfor %}
  </ol>
  <div class="carousel-inner">
    {% for banner in banners %} {% if forloop.counter == 1 %}
    <div class="carousel-item active">
      {% else %}
      <div class="carousel-item">
        {% endif %}
        <img
          src="/media/{{banner.img}}"
          width="100%"
          height="400px"
          alt="{{banner.alt}}"
        />
      </div>
      {% endfor %}
    </div>
    <a
      class="carousel-control-prev"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a
      class="carousel-control-next"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<main class="container my-4">
  <h3 class="my-4 border-bottom pb-1">Recent Products</h3>
  <div class="row">
    {% for product in data %}
    <div class="col-md-3 mb-4">
      <div class="card shadow">
        <a href="/product/{{product.slug}}/{{product.id}}"
          ><img
            src="/media/{{product.productattribute_set.first.image}}"
            class="card-img-top"
            alt="{{product.title}}"
            width="150px"
            height="150px"
        /></a>
        <div class="card-body">
          <h5 class="card-text">
            <a href="/product/{{product.slug}}/{{product.id}}"
              >{{product.title}}</a
            >
          </h5>
          <h6>
            $
            <span>{{product.productattribute_set.first.price}}</span>
          </h6>
        </div>
        <div class="card-footer">
          <strong>{{product.productattribute_set.first.color}}</strong>
          <input
            type="hidden"
            value="1"
            class="form-control product-qty-{{product.id}}"
            id="productQty"
          />
          <input
            type="hidden"
            class="product-image-{{product.id}}"
            value="{{product.productattribute_set.first.image}}"
          />
          <input
            type="hidden"
            class="product-id-{{product.id}}"
            value="{{product.id}}"
          />
          <input
            type="hidden"
            class="product-title-{{product.id}}"
            value="{{product.title}}"
          />
          <button
            class="btn btn-sm btn-primary add-to-cart"
            data-index="{{product.id}}"
          >
            <i class="fa fa-shopping-cart"></i>
          </button>
          {% if user.is_authenticated %}
          <button
            class="btn btn-sm btn-danger add-wishlist"
            data-product="{{product.id}}"
          >
            <i class="fa fa-heart"></i>
          </button>
          {% else %}
          <button class="btn btn-sm btn-danger disabled">
            <i class="fa fa-heart"></i>
          </button>
          {% endif %}
          <span class="float-right">
            4.5/5
            <i class="fa fa-star text-warning"></i>
          </span>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <p class="my-4 text-center">
    <a href="{% url 'product-list' %}" class="btn btn-dark btn-sm"
      >All Products <i class="fa fa-long-arrow-alt-right"></i
    ></a>
  </p>
</main>
{% endblock %}

main/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<!-- Featured Products -->
	<h3 class="my-4 border-bottom pb-1">{{data.title}}</h3>
	<div class="row">
		<!-- Images -->
		<div class="col-md-4">
			<img id="zoom_01" data-zoom-image="/media/{{data.dataattribute_set.first.image}}" src="/media/{{data.productattribute_set.first.image}}" class="card-img-top" alt="{{data.title}}">
		</div>
		<div class="col-md-8">
			<p>{{data.detail}}</p>
			<hr/>
			<table class="table table-bordered">
				<tr>
					<th>Colors</th>
					<td>
						{% for p_attr in data.productattribute_set.all %}
							<button class="btn btn-lg choose-color" data-color="{{color.color__id}}" style="background-color: {{p_attr.color.color_code}}"></button>
						{% endfor %}
					</td>
				</tr>
				<tr>
					<th>Sizes</th>
					<td>
						{% for p_attr in data.productattribute_set.all %}
						<button class="btn btn-secondary btn-md">{{p_attr.size}}</button>
						
					</td>
				</tr>
				<tr>
					<th>Price</th>
					<th>$ <span class="product-price-{{data.id}}">{{p_attr.price}}</span></th>
				</tr>
				{% endfor %}
			</table>
			<hr/>
			<div class="input-group my-3" style="width:30%;">
			  <input type="number" value="1" class="form-control product-qty-{{data.id}}" id="productQty" />
			  <div class="input-group-append">
			  	<input type="hidden" class="product-image-{{data.id}}" value="{{data.productattribute_set.first.image}}" />
		          <input type="hidden" class="product-id-{{data.id}}" value="{{data.id}}" />
		          <input type="hidden" class="product-title-{{data.id}}" value="{{data.title}}" />
			    <button class="btn btn-primary btn-sm add-to-cart" data-index="{{data.id}}" type="button" id="addToCartBtn"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
			  </div>
			</div>
		</div>
	</div>
	<hr />
	<div class="row">
		<div class="col-md-6">
			<h3 class="my-3">Detail</h3>
			<!-- Detail -->
			<table class="table table-bordered">
				<tr>
					<th>Brand</th>
					<td><a href="/brand-product-list/{{data.brand.id}}">{{data.brand.title}}</a></td>
				</tr>
				<tr>
					<th>Category</th>
					<td><a href="/category-product-list/{{data.category.id}}">{{data.category.title}}</a></td>
				</tr>
				<tr>
					<th>Specification</th>
					<td>{{data.specs}}</td>
				</tr>
			</table>
		</div>
	
			</h3>
	
		</div>
	</div>

<!-- Image Zoom -->
<script src="{% static 'jquery.ez-plus.js' %}"></script>
<script type="text/javascript">
    $('#zoom_01').ezPlus();
</script>

<!-- Add To Cart -->
<script src="{% static 'custom.js' %}"></script>

{% endblock %}

main/templates/product_list.html
{% extends 'base.html' %} {% load static %} {% block content %}
<main class="container my-4">
  <div class="row">
    <!-- Filters -->
    <div class="col-md-3">{% include 'filters.html' %}</div>
    <div class="col-md-9">
      <!-- Products -->
      <h3 class="mb-4 border-bottom pb-1">{{product_type}} Products</h3>
      <div class="row" id="filteredProducts">
        <p class="ajaxLoader">Loading...</p>
        {% for product in data %}
        <div class="col-lg-4 col-md-6 mb-4 product-box">
          <div class="card shadow">
            <a href="/product/{{product.slug}}/{{product.id}}"
              ><img
                src="/media/{{product.productattribute_set.first.image}}"
                class="card-img-top"
                alt="{{product.productattribute_set.first.title}}"
                width="150px"
                height="150px"
            /></a>
            <div class="card-body">
              <h5 class="card-text">
                <a href="/product/{{product.slug}}/{{product.id}}"
                  >{{product.title}}</a
                >
              </h5>
              <h6>
                $
                <span>{{product.productattribute_set.first.price}}</span>
              </h6>
            </div>
            <div class="card-footer">
              <input
                type="hidden"
                value="1"
                class="form-control product-qty-{{product.id}}"
                id="productQty"
              />
              <input
                type="hidden"
                class="product-image-{{product.id}}"
                value="{{product.productattribute_set.first.image}}"
              />
              <input
                type="hidden"
                class="product-id-{{product.id}}"
                value="{{product.id}}"
              />
              <input
                type="hidden"
                class="product-title-{{product.id}}"
                value="{{product.title}}"
              />
              <button
                class="btn btn-sm btn-primary add-to-cart"
                data-index="{{product.id}}"
              >
                <i class="fa fa-shopping-cart"></i>
              </button>
              <button class="btn btn-sm btn-danger">
                <i class="fa fa-heart"></i>
              </button>
              <span class="float-right">
                4.5/5
                <i class="fa fa-star text-warning"></i>
              </span>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <p class="my-4 text-center">
        <button
          id="loadMore"
          data-total="{{total_data}}"
          data-limit="3"
          class="btn btn-dark btn-sm"
        >
          Load More <i class="fa fa-sync load-more-icon"></i>
        </button>
      </p>
    </div>
  </div>
</main>
{% endblock %}